### ISSUE TITLE
Black style.

### ISSUE THREAD

**Issue by frederikhors** [keenethics/svelte-notifications#14]
It would be amazing to have a black style.

**Comment by rationalquality** [comment]
@frederikhors, you can make different styles just by abandoning the standard set. I don't think we can foresee all use cases. Probably, it would be nice to provide default styles for faster customization 🤔

**Comment by frederikhors** [comment]
Yes. I think just black & white ones.

**Comment by joelhickok** [comment]
The standard in the past for almost all toast or notification components has been to provide a standard theme set - although, of course, there are exceptions.  I found this Svelte component because I was not satisfied with the [Beyonk Adventures component ,](https://github.com/beyonk-adventures/svelte-notifications) which has very nice styling with themes like Info, Success, Warning, and so on, but NO positioning

This component offers positioning, but no themes or styles.  Yes, I know I can customize in my app, of course, but defaults go a long way.

Now I have to decide... do I submit a pull request for the Beyonk component to add positioning, or submit a pull request here to add basic themes.

**Comment by joelhickok** [comment]
And by the way, thank you for your work so far!

**Comment by rationalquality** [comment]
@joelhickok, I can add default types of notification. I'm a little busy right now, but I'll plan big update with a lot of changes in the near future

**Comment by rationalquality** [comment]
@joelhickok, please, check new release

**Comment by frederikhors** [comment]
@usernamus, am I wrong or the demo isn't update with the last update you mentioning here?

Also, can you write a little CHANGELOG.md?

Thanks. Great work!

**Comment by joelhickok** [comment]
I will check it out soon and update my project!  Thanks for the update!

**Comment by rationalquality** [comment]
@joelhickok, I will be glad to any feedback :)

@frederikhors, there are changes with styles and with a custom class for notification item
