### ISSUE TITLE
Cannot destructure property 'addNotification' of 'getNotificationsContext(...)' as it is undefined.

### ISSUE THREAD

**Issue by abh006** [keenethics/svelte-notifications#40]
I'm getting this error while accessing addNotification property.
```
Cannot destructure property 'addNotification' of 'getNotificationsContext(...)' as it is undefined.
```

**To Reproduce**
All I did is installed the package using `npm i --save svelte-notifications`
Then tried importing it from my `_layout.svelte`
```
import { getNotificationsContext } from 'svelte-notifications';
const { addNotification } = getNotificationsContext();
```

I tried printing the the value returned by `getNotificationsContext()` , and it was `undefined`.

**Comment by abh006** [comment]
See this [REPL](https://svelte.dev/repl/5aaf02e775fe4218894a6521d8b6c570?version=3.35.0)

**Comment by bagamanshin** [comment]
This functionality is available **after** initialization of **Notifications component**, not earlier

**Comment by silverdr** [comment]
Are there any examples of simple, single-component usage of `svelte-notifications`?

**Comment by TylerRick** [comment]
I've run into this limitation too. Is there any good reason why we couldn't/shouldn't allow using `svelte-notifications` to be used from a top-level component? It's currently only possible to use it (add/clear notifications) from child components of `Notifications`. But I would like to to clear notifications from my `client/src/routes/__layout.svelte` file (SvelteKit layout), which is the top-level component of my app. Conceptually, it seems like this should be allowed.

The problem seems to be that the store which is stored in the context in [Notifications.svelte](https://github.com/keenethics/svelte-notifications/blob/master/src/components/Notifications.svelte) here:
```js
  setContext(context, store);
```
is not made available via any other way _besides_ that context.

I tried importing it directly from [store](https://github.com/keenethics/svelte-notifications/blob/master/src/store/index.js), like this:
```js
import notificationsContext from 'svelte-notifications/src/store'
```
which gave me _an_ object with the right API, but it appeared to be a different instance, and interacting with it had no effect on the notifications displayed. 

I'm sure there's a way to make this store available programmatically. I'm just not sure what the best way is. Perhaps look at how other libraries do it?

Since there is no clean way provided by the library, I ended up exploring some ugly workarounds for getting access to that context/store object...

## Workaround 1: bind to child component, to pass context object from child up to top-level component

This worked (but is very ugly/undesirable IMHO)...

```svelte
// GetNotificationsStore.svelte
<script lang="ts">
  import { getNotificationsContext } from "svelte-notifications"

  export let notificationsStore = getNotificationsContext()
</script>
```

By the way, `getNotificationsContext` seems misnamed: it actually returns the store that was set _in_ the context by `setContext(context, store)`.

```svelte
// __layout.svelte
<Notifications>
  <GetNotificationsStore bind:notificationsStore />
  ...
</Notifications>

<script lang="ts">
  import Notifications, { getNotificationsContext } from 'svelte-notifications'
  let notificationsStore

  async function handleClick() {
    const { addNotification, clearNotifications } = notificationsStore
    clearNotifications()
    addNotification({ ... })
  }
</script>
```

## Proposed solution: Handle calling `setContext` ourselves in top-level component; change `Notifications` component to reuse that context

I tried separating the responsibility of _setting_ the context out of [Notifications.svelte](https://github.com/keenethics/svelte-notifications/blob/master/src/components/Notifications.svelte) and changing `Notifications.svelte` to simply _get_ the store out of that context and render the notifications in the store.

It only partly worked in my experiment, but I think it would work if I changed it in the actual library code.

```svelte
// __layout.svelte
<Notifications>
  ...
</Notifications>

<script lang="ts">
  import { setContext } from 'svelte';
  import { getNotificationsContext } from 'svelte-notifications'
  import notificationsContext from 'svelte-notifications/src/context'  
  import notificationsStore from 'svelte-notifications/src/store'  
  import Notifications from './Notifications.svelte'

  console.log('top-level notificationsContext', notificationsContext)
  console.log('top-level notificationsStore', notificationsStore)
  setContext(notificationsContext, notificationsStore)
  console.log('top-level getNotificationsContext', getNotificationsContext()) // this was undefined

  async function handleClick() {
    const { addNotification, clearNotifications } = notificationsStore
    clearNotifications()
    addNotification({ ... })
  }
</script>
```

And changing [Notifications.svelte](https://github.com/keenethics/svelte-notifications/blob/master/src/components/Notifications.svelte) to use `getContext` instead of `setContext`:

```svelte
<script lang="ts">
  import { getContext } from "svelte";
  import { getNotificationsContext } from "svelte-notifications"
  import notificationsContext from 'svelte-notifications/src/context'  

  // let store = getNotificationsContext()
  let store = getContext(notificationsContext)
  ...
```

I'm sure something like this could work. The only reason it didn't work for me was because the `getContext(context)` in `getNotificationsContext()` was seeing a different (but identical looking) instance of the `context` object than my top-level component was seeing, so `getNotificationsContext()` ended up returning undefined. How do I get the `import notificationsContext from 'svelte-notifications/src/context'` in my app code to reuse/see the same `context` object that the library uses in [context.js](https://github.com/keenethics/svelte-notifications/blob/master/src/context.js)?

### Questions


How could we provide the flexibility to do that while maintaining backward compatibility? 
Maybe change [Notifications.svelte](https://github.com/keenethics/svelte-notifications/blob/master/src/components/Notifications.svelte) to check if the context is already set and use it if it is, but fall back to setting it (the current behavior) if not? How would that work in the context of #30?

Does anyone have a better idea?


## Related issues:

- #30
- #50

**Comment by TylerRick** [comment]
By the way, I don't understand why the context key that we're using has this shape (which resembles the shape of the store that gets stored in context _under_ this key):

```js
const context = {
  subscribe: null,
  addNotification: null,
  removeNotification: null,
  clearNotifications: null,
};
```

It makes it look like we'll actually be later _using_ or updating those properties of the context key. But if I am not mistaken, this object is _only_ used as a key for `getContext`/`setContext` and any similarity with the shape of the store is merely coincidental, and misleading...

It seems like we could just as easily use a simple key like this in [context.js](https://github.com/keenethics/svelte-notifications/blob/master/src/context.js) instead:

```js
const contextKey = 'svelte-notifications';
export const getNotificationsStore = () => getContext(contextKey);
export default contextKey;
```

This would have also prevented the issue I ran into above where I was setting context using a `context` that looked identical to the one used by the library but it had a different object identity, so they were not seeing the same data. A primitive string would have never had that problem. :)

**Comment by rationalquality** [comment]
@TylerRick, context doesn't matter here. I'm now thinking of getting rid of it in favor of using just a store
